/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "foldingathome adapter settings": {
        en: "Adapter settings for foldingathome",
        de: "Adaptereinstellungen für foldingathome",
        ru: "Настройки адаптера для foldingathome",
        pt: "Configurações do adaptador para foldingathome",
        nl: "Adapterinstellingen voor foldingathome",
        fr: "Paramètres d'adaptateur pour foldingathome",
        it: "Impostazioni dell'adattatore per foldingathome",
        es: "Ajustes del adaptador para foldingathome",
        pl: "Ustawienia adaptera dla foldingathome",
        "zh-cn": "foldingathome的适配器设置",
    },
    foldingathome__host: {
        en: "Folding@home client host / ip",
        de: "Folding@home Client Host / IP",
        ru: "Folding@home client host / ip",
        pt: "Folding@home do cliente em casa / ip",
        nl: "Folding@home client host / ip",
        fr: "Hôte client IP / Folding@home",
        it: "Folding@home client host / ip",
        es: "Plegable @ host del cliente en casa / ip",
        pl: "Folding @ home host / ip klienta klienckiego",
        "zh-cn": "Folding @ home客户端主机/ ip",
    },
    foldingathome__port: {
        en: "Folding@home client port",
        de: "Folding@home Client Port",
        ru: "Порт клиента Folding@home",
        pt: "Porta do cliente Folding@home",
        nl: "Folding@home-clientpoort",
        fr: "Port client Folding @ home",
        it: "Porta client Folding@home",
        es: "Puerto de cliente Folding@home",
        pl: "Składany port klienta domowego",
        "zh-cn": "Folding@home客户端端口",
    },
    foldingathome__password: {
        en: "Folding@home client password",
        de: "Folding@home Client Passwort",
        ru: "Пароль Folding@home client",
        pt: "Senha do cliente Folding@home",
        nl: "Folding@home client wachtwoord",
        fr: "Mot de passe du client Folding@home",
        it: "Password del client Folding@home",
        es: "Contraseña de cliente plegable@home",
        pl: "Hasło klienta Folding@home",
        "zh-cn": "Folding@home客户端密码",
    },
};
